name: Frontend CI

on:
  pull_request:
    paths:
      - "frontend/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: frontend
        run: npm ci

      - name: Check formatting (fail on warnings)
        working-directory: frontend
        run: npm run prettier:ci'


      - name: Lint (fail on warnings)
        working-directory: frontend
        run: npm run lint:ci

      - name: Build
        working-directory: frontend
        run: npm run build
